version: '3'
services:
    newweb:
        image: infracloudio/csvserver
        privileged: true
        entrypoint:
                - "/usr/sbin/init"
        ports:
          - "9393:9300"
        environment:
          - CSVSERVER_BORDER=Orange
        container_name: "bharath"
