version: '3'
services:
    newweb:
        image: infracloudio/csvserver
        privileged: true
        entrypoint:
                - "/usr/sbin/init"    
        ports:
          - "9393:9300"
        environment:
          - CSVSERVER_BORDER=Orange
        container_name: "bharath"

    prom:
        image: prom/prometheus:v2.22.0
        privileged: true
        ports:
          - "9090:9090"
        container_name: prometheus
        volumes:
                - ./prom.yml:/etc/prometheus/prom.yml 
